version: "3"
services:
  coturn:
    image: coturn/coturn:alpine
    container_name: coturn
    restart: unless-stopped
    volumes:
      - ./coturn:/etc/coturn:Z
      - ./ssl:/etc/ssl/certs:Z
    network_mode: "host"
    user: "65534:65534"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    user: "999:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  acme:
    image: neilpang/acme.sh
    container_name: acme
    command: daemon
    volumes:
      - ./acme:/acme.sh
      - ./ssl:/ssl
    network_mode: "host"
    restart: unless-stopped

volumes:
  redis: